### ISSUE TITLE
Not callable with python -m

### ISSUE THREAD

**Issue by gitpushdashf** [kushaldas/asaman#10]
Just adding a `if __name__ == "__main__"` section should fix this so we can do `python -m asaman`.

**Comment by kushaldas** [comment]
I will update the codebase for this.

**Comment by kushaldas** [comment]
I guess I should just close this, people can just use the command line `asaman` tool as required.

**Comment by ntoll** [comment]
As far as I can tell, there is no need to `python -m asaman` since you can just directly call the `asaman` command. Not sure I understand the problem this change is trying to solve.

**Comment by gitpushdashf** [comment]
It's very common place to be able to call commands with `python -m`. `black`, `flake8`, `mypy`, `isort`, and `pytest` all support this.

It's nice because you know you're running something inside your Python virtual environment and not accidentally pulling in anything that's just in `$PATH`. There's also some Python packages that are only callable via the module, such as build. I think supporting both is handy.
