### ISSUE TITLE
Claim or consider asaman on PyPI

### ISSUE THREAD

**Issue by Julian** [kushaldas/asaman#2]
Hello! Thanks for making this.

I'm about to try it out, but I notice the package/distribution is called `amrasaman` while the binary/executable is called `asaman` -- I see [asaman is unclaimed](https://pypi.org/project/asaman/) on PyPI so perhaps it's worth at least making that redirect to `amrasaman` (via a package with trivial dependency) if you intend to keep the "true" distribution name as it is here. Users will undoubtedly try `pip install asaman` at some point.

And thanks again, looks like another useful addition to the packaging ecosystem.

**Comment by kushaldas** [comment]
Changed the full project name itself, otherwise it was creating a lot of confusion. Thank you for the issue. I am closing now.

You can now do:

`python3 -m pip install asaman`

**Comment by Julian** [comment]
Great!

**Comment by merwok** [comment]
What do the names mean?

**Comment by McSinyx** [comment]
FYI @kushaldas there is still one mention of amrasaman in the README:

https://github.com/kushaldas/asaman/blob/fc9b67b3f18e67198f278c90655a4471e3cb790e/README.md#L120-L123
